In [16]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

plt.style.use('seaborn')
X = np.arange(5) + 1
Y1 = np.array([0.5, 0.5, 0.75, 0.5, 0.5])
Y2 = np.random.random(5)*10
print(Y2)

[6.20632823 8.52097132 2.20606759 4.24031933 3.38870214]


/var/folders/yb/bpn5r9sd25x8hqqldtbxddg80000gn/T/ipykernel_52930/2199629468.py:5: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn')


In [37]:
live_on_kexp = pd.read_csv('live_on_kexp_2023.csv')
live_on_kexp

WEEK_NUMBER  WEEK_NUMBER_LIVE_SHOW                              ARTIST  \
0               1                      1                          TEKE::TEKE   
1               1                      4                Ibibio Sound Machine   
2               1                      7    King Gizzard & the Lizard Wizard   
3               1                      7  King Gizzard and the Lizard Wizard   
4               1                      8               Amyl and The Sniffers   
...           ...                    ...                                 ...   
1752           53                     34                       Kassa Overall   
1753           53                     46                        Spirit Award   
1754           53                     47              Black Belt Eagle Scout   
1755           53                     50                      The Budos Band   
1756           53                     51                  The Mountain Goats   

      PLAY_COUNT  PLAY_COUNT_BEFORE  PLAY_COUNT_AFTER  
0              5                  5                 0  
1              4                  4                 0  
2              2                  2                 0  
3              1                  1                 0  
4              2                  2                 0  
...          ...                ...               ...  
1752           1                  0                 1  
1753           2                  0                 2  
1754           1                  0                 1  
1755           4                  0                 4  
1756           1                  0                 1  

[1757 rows x 6 columns]

In [39]:
X = live_on_kexp["WEEK_NUMBER"]
Y1 = live_on_kexp["PLAY_COUNT_BEFORE"]
Y2 = live_on_kexp["PLAY_COUNT_AFTER"]


In [40]:
ax = plt.subplot()
ax.bar(X, Y1, label='Y1')
ax.bar(X, Y2, bottom=Y1, label='Y2')
plt.legend()
plt.show()

In [41]:
X

0        1
1        1
2        1
3        1
4        1
        ..
1752    53
1753    53
1754    53
1755    53
1756    53
Name: WEEK_NUMBER, Length: 1757, dtype: int64

In [12]:
Y1

array([0.5 , 0.5 , 0.75, 0.5 , 0.5 ])

In [13]:
Y2

array([0.00224425, 0.00749636, 0.0082752 , 0.00175114, 0.00803648])